'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { after, test } = require('node:test');
const { spawnSync } = require('node:child_process');

const cli = path.resolve(__dirname, '../bin/sdd-agentic-flow.js');
const packageRoot = path.resolve(__dirname, '..');
const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'sdd-agentic-flow-test-'));

after(() => fs.rmSync(temporary, { recursive: true, force: true }));

function run(args, cwd = temporary, input) {
  return spawnSync(process.execPath, [cli, ...args], { cwd, input, encoding: 'utf8' });
}

test('help, version, and list are available', () => {
  assert.match(run(['help']).stdout, /uninstall --plan/);
  assert.equal(run(['version']).stdout.trim(), '0.8.0');
  assert.match(run(['list']).stdout, /PACK core/);
});

test('init and install core are idempotent', () => {
  assert.equal(run(['init']).status, 0);
  assert.ok(fs.existsSync(path.join(temporary, '.sdd/config.yml')));
  assert.equal(run(['install', 'core']).status, 0);
  assert.match(run(['install', 'core']).stdout, /preserved/);
  assert.equal(run(['doctor']).status, 0);
});

test('interactive init writes selected safe configuration and preserves existing config', () => {
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'sdd-agentic-flow-interactive-'));
  const input =
    'task-app\nmain\ncodex\npt-BR\ngithub-guidance\nmulti\nlarge_feature\ntrue\nfalse\n';
  assert.equal(run(['init', '--interactive'], cwd, input).status, 0);
  const config = fs.readFileSync(path.join(cwd, '.sdd/config.yml'), 'utf8');
  assert.match(config, /name: task-app/);
  assert.match(config, /target: codex/);
  assert.match(config, /profile: pt-BR/);
  assert.match(config, /feature_profile: large_feature/);
  assert.match(config, /allow_multi_worktree: true/);
  assert.match(run(['init', '--interactive'], cwd, input).stdout, /will not overwrite/);
  fs.rmSync(cwd, { recursive: true, force: true });
});

test('init auto-discovers project context and discover refreshes it', () => {
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'sdd-agentic-flow-discover-'));
  fs.writeFileSync(path.join(cwd, 'README.md'), '# sample\n');
  fs.writeFileSync(path.join(cwd, 'AGENTS.md'), '# agents\n');
  fs.writeFileSync(path.join(cwd, 'package.json'), JSON.stringify({ name: 'sample-app' }));
  assert.equal(run(['init'], cwd).status, 0);
  const contextPath = path.join(cwd, '.sdd/context/project-context.md');
  assert.ok(fs.existsSync(contextPath));
  const initial = fs.readFileSync(contextPath, 'utf8');
  assert.match(initial, /Package name: sample-app/);
  assert.match(initial, /AGENTS\.md/);

  assert.match(run(['discover'], cwd).stdout, /preserved existing/);
  assert.equal(fs.readFileSync(contextPath, 'utf8'), initial);

  fs.writeFileSync(path.join(cwd, 'package.json'), JSON.stringify({ name: 'renamed-app' }));
  assert.match(
    run(['discover', '--force'], cwd).stdout,
    /created \.sdd\/context\/project-context\.md/,
  );
  assert.match(fs.readFileSync(contextPath, 'utf8'), /Package name: renamed-app/);

  assert.equal(run(['discover', '--unknown'], cwd).status, 1);
  fs.rmSync(cwd, { recursive: true, force: true });
});

test('discover detects architecture, CI, and platform signals', () => {
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'sdd-agentic-flow-discover2-'));
  fs.mkdirSync(path.join(cwd, 'src/domain'), { recursive: true });
  fs.mkdirSync(path.join(cwd, '.github/workflows'), { recursive: true });
  fs.writeFileSync(path.join(cwd, '.github/workflows/ci.yml'), 'name: ci\n');
  fs.mkdirSync(path.join(cwd, 'prisma'), { recursive: true });
  fs.writeFileSync(path.join(cwd, 'prisma/schema.prisma'), 'datasource db {}\n');
  assert.equal(run(['init'], cwd).status, 0);
  const context = fs.readFileSync(path.join(cwd, '.sdd/context/project-context.md'), 'utf8');
  assert.match(context, /## Architecture signals/);
  assert.match(context, /src\/domain/);
  assert.match(context, /## CI\/CD signals/);
  assert.match(context, /\.github\/workflows/);
  assert.match(context, /## Platform signals/);
  assert.match(context, /prisma\/schema\.prisma/);
  fs.rmSync(cwd, { recursive: true, force: true });
});

test('project-context.md carries provenance metadata, gracefully, outside a git repo', () => {
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'sdd-agentic-flow-provenance-'));
  assert.equal(run(['init'], cwd).status, 0);
  const contextPath = path.join(cwd, '.sdd/context/project-context.md');
  const content = fs.readFileSync(contextPath, 'utf8');
  assert.match(content, /> Generated by sdd-agentic-flow 0\.8\.0/);
  assert.match(content, /> Generated at: \d{4}-\d{2}-\d{2}T/);
  assert.match(content, /> Repository revision: not a git repository/);
  assert.match(content, /> Branch: unknown/);
  fs.rmSync(cwd, { recursive: true, force: true });
});

test('context status reports not found, then available, without mutating on status alone', () => {
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'sdd-agentic-flow-context-status-'));
  assert.match(run(['context'], cwd).stdout, /status: not found/);
  assert.equal(run(['init'], cwd).status, 0);
  const contextPath = path.join(cwd, '.sdd/context/project-context.md');
  const before = fs.readFileSync(contextPath, 'utf8');
  const status = run(['context', 'status'], cwd).stdout;
  assert.match(status, /status: available/);
  assert.match(status, /generated at:/);
  assert.match(status, /repository revision: not a git repository/);
  assert.equal(fs.readFileSync(contextPath, 'utf8'), before);
  assert.equal(run(['context', 'status', 'extra'], cwd).status, 1);
  assert.equal(run(['context', 'bogus'], cwd).status, 1);
  fs.rmSync(cwd, { recursive: true, force: true });
});

test('context refresh regenerates unconditionally, matching discover --force', () => {
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'sdd-agentic-flow-context-refresh-'));
  fs.writeFileSync(path.join(cwd, 'package.json'), JSON.stringify({ name: 'first-name' }));
  assert.equal(run(['init'], cwd).status, 0);
  const contextPath = path.join(cwd, '.sdd/context/project-context.md');
  fs.writeFileSync(path.join(cwd, 'package.json'), JSON.stringify({ name: 'second-name' }));
  assert.match(
    run(['context', 'refresh'], cwd).stdout,
    /created \.sdd\/context\/project-context\.md/,
  );
  assert.match(fs.readFileSync(contextPath, 'utf8'), /Package name: second-name/);
  fs.rmSync(cwd, { recursive: true, force: true });
});

test('context status detects repository revision drift in a real git repository', (t) => {
  if (spawnSync('git', ['--version']).status !== 0) {
    t.skip('git CLI not available in this environment');
    return;
  }
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'sdd-agentic-flow-context-git-'));
  const git = (gitArgs) => spawnSync('git', gitArgs, { cwd, encoding: 'utf8' });
  git(['init', '-q']);
  git(['config', 'user.email', 'test@example.com']);
  git(['config', 'user.name', 'Test']);
  fs.writeFileSync(path.join(cwd, 'README.md'), '# sample\n');
  git(['add', 'README.md']);
  git(['commit', '-q', '-m', 'init']);

  assert.equal(run(['init'], cwd).status, 0);
  const fresh = run(['context', 'status'], cwd).stdout;
  assert.match(fresh, /repository revision: [0-9a-f]{7,40}/);
  assert.match(fresh, /branch: /);
  assert.doesNotMatch(fresh, /Repository has changed/);

  fs.appendFileSync(path.join(cwd, 'README.md'), 'more\n');
  git(['add', 'README.md']);
  git(['commit', '-q', '-m', 'change']);

  const drifted = run(['context', 'status'], cwd).stdout;
  assert.match(drifted, /Repository has changed since context generation\./);
  assert.match(drifted, /Recommendation: run `sdd-agentic-flow context refresh`\./);

  const doctorReport = JSON.parse(run(['doctor', '--json'], cwd).stdout);
  assert.match(
    doctorReport.checks.find((check) => check.name === 'project_context').message,
    /repository has changed since generation/,
  );

  assert.match(
    run(['context', 'refresh'], cwd).stdout,
    /created \.sdd\/context\/project-context\.md/,
  );
  const refreshed = run(['context', 'status'], cwd).stdout;
  assert.doesNotMatch(refreshed, /Repository has changed/);

  fs.rmSync(cwd, { recursive: true, force: true });
});

test('doctor JSON is parseable and smoke is isolated', () => {
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'sdd-agentic-flow-doctor-'));
  assert.equal(run(['init', '--language', 'pt-BR'], cwd).status, 0);
  assert.equal(run(['install', 'core'], cwd).status, 0);
  const result = run(['doctor', '--json'], cwd);
  const report = JSON.parse(result.stdout);
  assert.equal(report.version, '0.8.0');
  assert.ok(Array.isArray(report.checks));
  assert.equal(report.language.profile, 'pt-BR');
  assert.equal(report.language.status, 'PASS');
  assert.equal(report.checks.find((check) => check.name === 'project_context').status, 'PASS');
  assert.equal(report.checks.find((check) => check.name === 'baseline-tlc').status, 'PASS');
  assert.equal(report.checks.find((check) => check.name === 'adaptive-sizing').status, 'PASS');
  assert.equal(report.checks.find((check) => check.name === 'traceability').status, 'PASS');
  assert.equal(report.checks.find((check) => check.name === 'evidence-first').status, 'PASS');
  assert.equal(report.checks.find((check) => check.name === 'artifact-contracts').status, 'PASS');
  assert.ok(
    fs.existsSync(
      path.join(cwd, '.agents/skills/sdd-agentic-flow-shared/references/artifact-contracts.md'),
    ),
  );
  assert.equal(run(['doctor', '--smoke'], cwd).status, 0);
  fs.rmSync(cwd, { recursive: true, force: true });
});

test('doctor --contracts validates installed capability contracts', () => {
  assert.match(run(['help']).stdout, /--contracts/);

  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'sdd-agentic-flow-contracts-'));
  assert.equal(run(['init'], cwd).status, 0);
  const warnReport = JSON.parse(run(['doctor', '--json', '--contracts'], cwd).stdout);
  const warnCheck = warnReport.checks.find((check) => check.name === 'capability_contracts');
  assert.equal(warnCheck.status, 'WARN');
  assert.match(warnCheck.message, /no installed skills/);

  assert.equal(run(['install', 'core'], cwd).status, 0);
  const passReport = JSON.parse(run(['doctor', '--json', '--contracts'], cwd).stdout);
  assert.equal(
    passReport.checks.find((check) => check.name === 'capability_contracts').status,
    'PASS',
  );

  const corruptedSkill = path.join(cwd, '.agents/skills/sdd-create-specs/SKILL.md');
  const original = fs.readFileSync(corruptedSkill, 'utf8');
  fs.writeFileSync(corruptedSkill, original.replace(/^produces:.*$/m, ''));
  const failReport = JSON.parse(run(['doctor', '--json', '--contracts'], cwd).stdout);
  const failCheck = failReport.checks.find((check) => check.name === 'capability_contracts');
  assert.equal(failCheck.status, 'FAIL');
  assert.match(failCheck.message, /sdd-create-specs/);
  assert.match(failCheck.message, /produces/);

  fs.rmSync(cwd, { recursive: true, force: true });
});

test('doctor --contracts detects dangling depends_on references', () => {
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'sdd-agentic-flow-contracts-dangling-'));
  assert.equal(run(['init'], cwd).status, 0);
  assert.equal(run(['install', 'core'], cwd).status, 0);
  const skillPath = path.join(cwd, '.agents/skills/sdd-create-specs/SKILL.md');
  const original = fs.readFileSync(skillPath, 'utf8');
  fs.writeFileSync(skillPath, original.replace('depends_on: []', 'depends_on: [not-a-real-skill]'));
  const report = JSON.parse(run(['doctor', '--json', '--contracts'], cwd).stdout);
  const check = report.checks.find((c) => c.name === 'capability_contracts');
  assert.equal(check.status, 'FAIL');
  assert.match(check.message, /depends_on references unknown skill 'not-a-real-skill'/);
  fs.rmSync(cwd, { recursive: true, force: true });
});

test('doctor --contracts detects a depends_on cycle between installed skills', () => {
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'sdd-agentic-flow-contracts-cycle-'));
  assert.equal(run(['init'], cwd).status, 0);
  assert.equal(run(['install', 'core'], cwd).status, 0);
  const specsPath = path.join(cwd, '.agents/skills/sdd-create-specs/SKILL.md');
  const taskCheckPath = path.join(cwd, '.agents/skills/sdd-task-check/SKILL.md');
  fs.writeFileSync(
    specsPath,
    fs.readFileSync(specsPath, 'utf8').replace('depends_on: []', 'depends_on: [sdd-task-check]'),
  );
  fs.writeFileSync(
    taskCheckPath,
    fs
      .readFileSync(taskCheckPath, 'utf8')
      .replace('depends_on: []', 'depends_on: [sdd-create-specs]'),
  );
  const report = JSON.parse(run(['doctor', '--json', '--contracts'], cwd).stdout);
  const check = report.checks.find((c) => c.name === 'capability_contracts');
  assert.equal(check.status, 'FAIL');
  assert.match(check.message, /contract cycle detected/);
  assert.match(check.message, /sdd-create-specs/);
  assert.match(check.message, /sdd-task-check/);
  fs.rmSync(cwd, { recursive: true, force: true });
});

test('doctor --contracts flags conflicting skills that are both installed', () => {
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'sdd-agentic-flow-contracts-conflict-'));
  assert.equal(run(['init'], cwd).status, 0);
  assert.equal(run(['install', 'core'], cwd).status, 0);
  const skillPath = path.join(cwd, '.agents/skills/sdd-create-specs/SKILL.md');
  const original = fs.readFileSync(skillPath, 'utf8');
  fs.writeFileSync(skillPath, original.replace('conflicts: []', 'conflicts: [sdd-task-check]'));
  const report = JSON.parse(run(['doctor', '--json', '--contracts'], cwd).stdout);
  const check = report.checks.find((c) => c.name === 'capability_contracts');
  assert.equal(check.status, 'FAIL');
  assert.match(check.message, /sdd-create-specs and sdd-task-check declare a conflict/);
  fs.rmSync(cwd, { recursive: true, force: true });
});

test('doctor --contracts detects an unknown baseline id', () => {
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'sdd-agentic-flow-contracts-baseline-'));
  assert.equal(run(['init'], cwd).status, 0);
  assert.equal(run(['install', 'core'], cwd).status, 0);
  const skillPath = path.join(cwd, '.agents/skills/sdd-create-specs/SKILL.md');
  const original = fs.readFileSync(skillPath, 'utf8');
  fs.writeFileSync(
    skillPath,
    original.replace('baseline: [tlc-spec-driven]', 'baseline: [not-a-real-baseline]'),
  );
  const report = JSON.parse(run(['doctor', '--json', '--contracts'], cwd).stdout);
  const check = report.checks.find((c) => c.name === 'capability_contracts');
  assert.equal(check.status, 'FAIL');
  assert.match(check.message, /baseline references unknown baseline id 'not-a-real-baseline'/);
  fs.rmSync(cwd, { recursive: true, force: true });
});

test('feature profile flag configures workflow and invalid values fail', () => {
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'sdd-agentic-flow-feature-profile-'));
  assert.equal(run(['init', '--feature-profile', 'epic'], cwd).status, 0);
  assert.match(fs.readFileSync(path.join(cwd, '.sdd/config.yml'), 'utf8'), /feature_profile: epic/);
  const invalidCwd = fs.mkdtempSync(path.join(os.tmpdir(), 'sdd-agentic-flow-feature-invalid-'));
  assert.equal(run(['init', '--feature-profile', 'huge'], invalidCwd).status, 1);
  fs.rmSync(cwd, { recursive: true, force: true });
  fs.rmSync(invalidCwd, { recursive: true, force: true });
});

test('doctor validates the TDD baseline in package and installed shared layers', () => {
  const packageReport = JSON.parse(run(['doctor', '--json'], packageRoot).stdout);
  assert.equal(packageReport.status, 'PASS');
  assert.ok(packageReport.checks.some((check) => check.name === 'tdd-baseline'));

  for (const pack of ['core', 'execution']) {
    const cwd = fs.mkdtempSync(path.join(os.tmpdir(), `sdd-agentic-flow-tdd-${pack}-`));
    assert.equal(run(['init'], cwd).status, 0);
    assert.equal(run(['install', pack], cwd).status, 0);
    assert.ok(
      fs.existsSync(
        path.join(cwd, '.agents/skills/sdd-agentic-flow-shared/references/tdd-baseline.md'),
      ),
    );
    const report = JSON.parse(run(['doctor', '--json'], cwd).stdout);
    assert.equal(report.checks.find((check) => check.name === 'tdd-baseline').status, 'PASS');
    fs.rmSync(cwd, { recursive: true, force: true });
  }
});

test('routing skill is listed, installed by public packs, and removed by uninstall', () => {
  assert.match(run(['list']).stdout, /sdd-route/);

  for (const pack of ['core', 'planning', 'execution', 'pr']) {
    const cwd = fs.mkdtempSync(path.join(os.tmpdir(), `sdd-agentic-flow-route-${pack}-`));
    assert.equal(run(['init'], cwd).status, 0);
    assert.equal(run(['install', pack], cwd).status, 0);
    assert.ok(fs.existsSync(path.join(cwd, '.agents/skills/sdd-route/SKILL.md')));
    fs.rmSync(cwd, { recursive: true, force: true });
  }

  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'sdd-agentic-flow-route-uninstall-'));
  assert.equal(run(['init'], cwd).status, 0);
  assert.equal(run(['install', 'core'], cwd).status, 0);
  assert.equal(run(['uninstall', '--apply'], cwd).status, 0);
  assert.ok(!fs.existsSync(path.join(cwd, '.agents/skills/sdd-route')));
  assert.ok(fs.existsSync(path.join(cwd, '.sdd/config.yml')));
  assert.ok(fs.existsSync(path.join(cwd, '.specs/features')));
  fs.rmSync(cwd, { recursive: true, force: true });
});

test('language flag generates profiles and invalid values fail', () => {
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'sdd-agentic-flow-language-'));
  assert.equal(run(['init', '--language', 'pt-BR'], cwd).status, 0);
  const config = fs.readFileSync(path.join(cwd, '.sdd/config.yml'), 'utf8');
  assert.match(config, /profile: pt-BR/);
  assert.match(config, /bilingual_mode: technical-canonical/);
  const invalidCwd = fs.mkdtempSync(path.join(os.tmpdir(), 'sdd-agentic-flow-invalid-'));
  assert.equal(run(['init', '--language', 'de-DE'], invalidCwd).status, 1);
  fs.rmSync(cwd, { recursive: true, force: true });
  fs.rmSync(invalidCwd, { recursive: true, force: true });
});

test('interactive language default and legacy config warning are supported', () => {
  const interactiveCwd = fs.mkdtempSync(
    path.join(os.tmpdir(), 'sdd-agentic-flow-language-interactive-'),
  );
  const input = 'language-app\nmain\ngeneric\n\nlocal-files\nsingle\n\nfalse\nfalse\n';
  assert.equal(
    run(['init', '--interactive', '--language', 'pt-BR'], interactiveCwd, input).status,
    0,
  );
  const interactiveConfig = fs.readFileSync(path.join(interactiveCwd, '.sdd/config.yml'), 'utf8');
  assert.match(interactiveConfig, /profile: pt-BR/);
  assert.match(interactiveConfig, /feature_profile: medium_feature/);
  fs.rmSync(interactiveCwd, { recursive: true, force: true });

  const legacyCwd = fs.mkdtempSync(path.join(os.tmpdir(), 'sdd-agentic-flow-language-legacy-'));
  fs.mkdirSync(path.join(legacyCwd, '.sdd'), { recursive: true });
  fs.writeFileSync(
    path.join(legacyCwd, '.sdd/config.yml'),
    'language:\n  human_outputs: en-US\n  technical_tokens: canonical\n',
  );
  const report = JSON.parse(run(['doctor', '--json'], legacyCwd).stdout);
  assert.equal(report.language.status, 'WARN');
  assert.equal(report.language.profile, null);
  fs.rmSync(legacyCwd, { recursive: true, force: true });
});

test('uninstall plans and removes only toolkit assets', () => {
  assert.match(run(['uninstall', '--plan']).stdout, /sdd-agentic-flow-shared/);
  assert.equal(run(['uninstall', '--apply']).status, 0);
  assert.ok(fs.existsSync(path.join(temporary, '.sdd/config.yml')));
  assert.ok(fs.existsSync(path.join(temporary, '.specs/features')));
  assert.ok(!fs.existsSync(path.join(temporary, '.agents/skills/sdd-agentic-flow-shared')));
  assert.equal(run(['uninstall', '--apply', '--include-config']).status, 0);
  assert.ok(!fs.existsSync(path.join(temporary, '.sdd/config.yml')));
});

test('invalid packs and flags fail', () => {
  assert.equal(run(['install', 'missing-pack']).status, 1);
  assert.equal(run(['uninstall']).status, 1);
  assert.equal(run(['doctor', '--unknown']).status, 1);
});

test('a real npm pack tarball installs and its extracted CLI passes init/discover/install/doctor', (t) => {
  if (spawnSync('tar', ['--version']).status !== 0) {
    t.skip('tar CLI not available in this environment');
    return;
  }

  const packDir = fs.mkdtempSync(path.join(os.tmpdir(), 'sdd-agentic-flow-pack-'));
  const cacheDir = fs.mkdtempSync(path.join(os.tmpdir(), 'sdd-agentic-flow-pack-cache-'));
  const extractDir = fs.mkdtempSync(path.join(os.tmpdir(), 'sdd-agentic-flow-extract-'));
  const consumerDir = fs.mkdtempSync(path.join(os.tmpdir(), 'sdd-agentic-flow-pack-consumer-'));

  try {
    const pack = spawnSync(
      'npm',
      ['pack', '--json', '--pack-destination', packDir, '--cache', cacheDir],
      { cwd: packageRoot, encoding: 'utf8' },
    );
    assert.equal(pack.status, 0, pack.stderr);
    const jsonStart = pack.stdout.indexOf('[');
    const [meta] = JSON.parse(pack.stdout.slice(jsonStart));
    const tarballPath = path.join(packDir, meta.filename);
    assert.ok(fs.existsSync(tarballPath));

    const extract = spawnSync('tar', ['-xzf', tarballPath, '-C', extractDir]);
    assert.equal(extract.status, 0, extract.stderr);

    const installedCli = path.join(extractDir, 'package', 'bin', 'sdd-agentic-flow.js');
    assert.ok(fs.existsSync(installedCli));
    assert.notEqual(installedCli, cli);

    assert.ok(!fs.existsSync(path.join(extractDir, 'package', 'test')));

    const runPacked = (args, input) =>
      spawnSync(process.execPath, [installedCli, ...args], {
        cwd: consumerDir,
        input,
        encoding: 'utf8',
      });

    assert.equal(runPacked(['version']).stdout.trim(), '0.8.0');
    assert.equal(runPacked(['init']).status, 0);
    assert.equal(runPacked(['discover']).status, 0);
    assert.equal(runPacked(['install', 'core']).status, 0);

    const doctorResult = runPacked(['doctor', '--contracts', '--json']);
    assert.equal(doctorResult.status, 0);
    const report = JSON.parse(doctorResult.stdout);
    assert.equal(
      report.checks.find((check) => check.name === 'capability_contracts').status,
      'PASS',
    );
    assert.equal(report.checks.find((check) => check.name === 'skills').status, 'PASS');
    assert.equal(report.checks.find((check) => check.name === 'shared_layer').status, 'PASS');
  } finally {
    for (const dir of [packDir, cacheDir, extractDir, consumerDir])
      fs.rmSync(dir, { recursive: true, force: true });
  }
});
