import type { BrandMotionRole } from './brand-motion';

export type GeneratedBrandMotionRole = BrandMotionRole;
export const CANONICAL_BRAND_WIDTH = 80 as const;
export const CANONICAL_BRAND_HEIGHT = 34 as const;
export const CANONICAL_BRAND_MASK = [
  [],
  [],
  [],
  [[46, 47, 'large']],
  [[46, 49, 'large']],
  [[46, 51, 'large']],
  [[46, 53, 'large']],
  [[46, 55, 'large']],
  [[46, 57, 'large']],
  [[22, 22, 'medium'], [46, 59, 'large']],
  [[22, 25, 'medium'], [46, 61, 'large']],
  [[22, 27, 'medium'], [46, 62, 'large']],
  [[22, 30, 'medium'], [46, 64, 'large']],
  [[22, 32, 'medium'], [46, 66, 'large']],
  [[6, 8, 'small'], [22, 35, 'medium'], [46, 68, 'large']],
  [[6, 12, 'small'], [22, 37, 'medium'], [46, 70, 'large']],
  [[6, 15, 'small'], [22, 40, 'medium'], [46, 72, 'large']],
  [[6, 15, 'small'], [22, 40, 'medium'], [46, 72, 'large']],
  [[6, 12, 'small'], [22, 37, 'medium'], [46, 70, 'large']],
  [[6, 8, 'small'], [22, 35, 'medium'], [46, 68, 'large']],
  [[22, 32, 'medium'], [46, 66, 'large']],
  [[22, 30, 'medium'], [46, 64, 'large']],
  [[22, 27, 'medium'], [46, 62, 'large']],
  [[22, 25, 'medium'], [46, 61, 'large']],
  [[22, 22, 'medium'], [46, 59, 'large']],
  [[46, 57, 'large']],
  [[46, 55, 'large']],
  [[46, 53, 'large']],
  [[46, 51, 'large']],
  [[46, 49, 'large']],
  [[46, 47, 'large']],
  [],
  [],
  [],
] as const;
export const BRAND_ANIMATION = { width: 80, height: 34, frames: [
  { durationMs: 50, rows: [
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    []
  ] },
  { durationMs: 55, rows: [
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [{ column: 6, text: '*', role: 'flow.energy' }],
    [{ column: 6, text: '*', role: 'flow.energy' }, { column: 7, text: ':.', role: 'flow.dim' }],
    [{ column: 6, text: '*+', role: 'flow.energy' }, { column: 8, text: ':.', role: 'flow.dim' }],
    [{ column: 6, text: '*+', role: 'flow.energy' }, { column: 8, text: ':.', role: 'flow.dim' }],
    [{ column: 6, text: '*', role: 'flow.energy' }, { column: 7, text: ':.', role: 'flow.dim' }],
    [{ column: 6, text: '*', role: 'flow.energy' }],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    []
  ] },
  { durationMs: 60, rows: [
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [{ column: 22, text: '.', role: 'flow.dim' }],
    [{ column: 22, text: '.', role: 'flow.dim' }],
    [{ column: 22, text: '.', role: 'flow.dim' }],
    [{ column: 22, text: '.', role: 'flow.dim' }],
    [{ column: 22, text: '.', role: 'flow.dim' }],
    [{ column: 6, text: '@', role: 'flow.highlight' }, { column: 7, text: '+', role: 'flow.energy' }, { column: 22, text: '..', role: 'flow.dim' }],
    [{ column: 6, text: '@', role: 'flow.highlight' }, { column: 7, text: '%*+', role: 'flow.energy' }, { column: 10, text: '.', role: 'flow.dim' }, { column: 22, text: '..', role: 'flow.dim' }],
    [{ column: 6, text: '@', role: 'flow.highlight' }, { column: 7, text: '%#*+', role: 'flow.energy' }, { column: 11, text: ':.', role: 'flow.dim' }, { column: 22, text: '..', role: 'flow.dim' }],
    [{ column: 6, text: '@', role: 'flow.highlight' }, { column: 7, text: '%#*+', role: 'flow.energy' }, { column: 11, text: ':.', role: 'flow.dim' }, { column: 22, text: '..', role: 'flow.dim' }],
    [{ column: 6, text: '@', role: 'flow.highlight' }, { column: 7, text: '%*+', role: 'flow.energy' }, { column: 10, text: '.', role: 'flow.dim' }, { column: 22, text: '..', role: 'flow.dim' }],
    [{ column: 6, text: '@', role: 'flow.highlight' }, { column: 7, text: '+', role: 'flow.energy' }, { column: 22, text: '..', role: 'flow.dim' }],
    [{ column: 22, text: '.', role: 'flow.dim' }],
    [{ column: 22, text: '.', role: 'flow.dim' }],
    [{ column: 22, text: '.', role: 'flow.dim' }],
    [{ column: 22, text: '.', role: 'flow.dim' }],
    [{ column: 22, text: '.', role: 'flow.dim' }],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    []
  ] },
  { durationMs: 65, rows: [
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [{ column: 22, text: '#', role: 'flow.energy' }],
    [{ column: 22, text: '#', role: 'flow.energy' }, { column: 23, text: ':', role: 'flow.dim' }],
    [{ column: 22, text: '#+', role: 'flow.energy' }, { column: 24, text: '.', role: 'flow.dim' }],
    [{ column: 22, text: '#*', role: 'flow.energy' }, { column: 24, text: ':.', role: 'flow.dim' }],
    [{ column: 22, text: '#*+', role: 'flow.energy' }, { column: 25, text: ':.', role: 'flow.dim' }],
    [{ column: 6, text: '█', role: 'brand.small' }, { column: 7, text: '%', role: 'flow.energy' }, { column: 8, text: '.', role: 'flow.dim' }, { column: 22, text: '#*++', role: 'flow.energy' }, { column: 26, text: ':.', role: 'flow.dim' }],
    [{ column: 6, text: '██', role: 'brand.small' }, { column: 8, text: '@', role: 'flow.highlight' }, { column: 9, text: '%*+', role: 'flow.energy' }, { column: 12, text: '.', role: 'flow.dim' }, { column: 22, text: '#*++', role: 'flow.energy' }, { column: 26, text: '::.', role: 'flow.dim' }],
    [{ column: 6, text: '███', role: 'brand.small' }, { column: 9, text: '@', role: 'flow.highlight' }, { column: 10, text: '%#*+', role: 'flow.energy' }, { column: 14, text: ':.', role: 'flow.dim' }, { column: 22, text: '#**++', role: 'flow.energy' }, { column: 27, text: '::..', role: 'flow.dim' }],
    [{ column: 6, text: '███', role: 'brand.small' }, { column: 9, text: '@', role: 'flow.highlight' }, { column: 10, text: '%#*+', role: 'flow.energy' }, { column: 14, text: ':.', role: 'flow.dim' }, { column: 22, text: '#**++', role: 'flow.energy' }, { column: 27, text: '::..', role: 'flow.dim' }],
    [{ column: 6, text: '██', role: 'brand.small' }, { column: 8, text: '@', role: 'flow.highlight' }, { column: 9, text: '%*+', role: 'flow.energy' }, { column: 12, text: '.', role: 'flow.dim' }, { column: 22, text: '#*++', role: 'flow.energy' }, { column: 26, text: '::.', role: 'flow.dim' }],
    [{ column: 6, text: '█', role: 'brand.small' }, { column: 7, text: '%', role: 'flow.energy' }, { column: 8, text: '.', role: 'flow.dim' }, { column: 22, text: '#*++', role: 'flow.energy' }, { column: 26, text: ':.', role: 'flow.dim' }],
    [{ column: 22, text: '#*+', role: 'flow.energy' }, { column: 25, text: ':.', role: 'flow.dim' }],
    [{ column: 22, text: '#*', role: 'flow.energy' }, { column: 24, text: ':.', role: 'flow.dim' }],
    [{ column: 22, text: '#+', role: 'flow.energy' }, { column: 24, text: '.', role: 'flow.dim' }],
    [{ column: 22, text: '#', role: 'flow.energy' }, { column: 23, text: ':', role: 'flow.dim' }],
    [{ column: 22, text: '#', role: 'flow.energy' }],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    []
  ] },
  { durationMs: 65, rows: [
    [],
    [],
    [],
    [{ column: 46, text: ':', role: 'flow.dim' }],
    [{ column: 46, text: ':', role: 'flow.dim' }],
    [{ column: 46, text: ':', role: 'flow.dim' }],
    [{ column: 46, text: ':.', role: 'flow.dim' }],
    [{ column: 46, text: ':.', role: 'flow.dim' }],
    [{ column: 46, text: ':.', role: 'flow.dim' }],
    [{ column: 22, text: '█', role: 'brand.medium' }, { column: 46, text: ':..', role: 'flow.dim' }],
    [{ column: 22, text: '█', role: 'brand.medium' }, { column: 23, text: '#', role: 'flow.energy' }, { column: 24, text: ':', role: 'flow.dim' }, { column: 46, text: ':..', role: 'flow.dim' }],
    [{ column: 22, text: '█', role: 'brand.medium' }, { column: 23, text: '%*+', role: 'flow.energy' }, { column: 26, text: '.', role: 'flow.dim' }, { column: 46, text: '::.', role: 'flow.dim' }],
    [{ column: 22, text: '█', role: 'brand.medium' }, { column: 23, text: '@', role: 'flow.highlight' }, { column: 24, text: '%#+', role: 'flow.energy' }, { column: 27, text: ':.', role: 'flow.dim' }, { column: 46, text: '::..', role: 'flow.dim' }],
    [{ column: 22, text: '█', role: 'brand.medium' }, { column: 23, text: '@', role: 'flow.highlight' }, { column: 24, text: '%#*++', role: 'flow.energy' }, { column: 29, text: ':.', role: 'flow.dim' }, { column: 46, text: '::..', role: 'flow.dim' }],
    [{ column: 6, text: '██', role: 'brand.small' }, { column: 8, text: '#', role: 'flow.energy' }, { column: 22, text: '█', role: 'brand.medium' }, { column: 23, text: '@@', role: 'flow.highlight' }, { column: 25, text: '%#**+', role: 'flow.energy' }, { column: 30, text: '::.', role: 'flow.dim' }, { column: 46, text: '::..', role: 'flow.dim' }],
    [{ column: 6, text: '█████', role: 'brand.small' }, { column: 11, text: '%#', role: 'flow.energy' }, { column: 22, text: '█', role: 'brand.medium' }, { column: 23, text: '@@', role: 'flow.highlight' }, { column: 25, text: '%%#**++', role: 'flow.energy' }, { column: 32, text: ':..', role: 'flow.dim' }, { column: 46, text: '::...', role: 'flow.dim' }],
    [{ column: 6, text: '███████', role: 'brand.small' }, { column: 13, text: '@', role: 'flow.highlight' }, { column: 14, text: '%#', role: 'flow.energy' }, { column: 22, text: '█', role: 'brand.medium' }, { column: 23, text: '@@', role: 'flow.highlight' }, { column: 25, text: '%%##**++', role: 'flow.energy' }, { column: 33, text: '::..', role: 'flow.dim' }, { column: 46, text: '::...', role: 'flow.dim' }],
    [{ column: 6, text: '███████', role: 'brand.small' }, { column: 13, text: '@', role: 'flow.highlight' }, { column: 14, text: '%#', role: 'flow.energy' }, { column: 22, text: '█', role: 'brand.medium' }, { column: 23, text: '@@', role: 'flow.highlight' }, { column: 25, text: '%%##**++', role: 'flow.energy' }, { column: 33, text: '::..', role: 'flow.dim' }, { column: 46, text: '::...', role: 'flow.dim' }],
    [{ column: 6, text: '█████', role: 'brand.small' }, { column: 11, text: '%#', role: 'flow.energy' }, { column: 22, text: '█', role: 'brand.medium' }, { column: 23, text: '@@', role: 'flow.highlight' }, { column: 25, text: '%%#**++', role: 'flow.energy' }, { column: 32, text: ':..', role: 'flow.dim' }, { column: 46, text: '::...', role: 'flow.dim' }],
    [{ column: 6, text: '██', role: 'brand.small' }, { column: 8, text: '#', role: 'flow.energy' }, { column: 22, text: '█', role: 'brand.medium' }, { column: 23, text: '@@', role: 'flow.highlight' }, { column: 25, text: '%#**+', role: 'flow.energy' }, { column: 30, text: '::.', role: 'flow.dim' }, { column: 46, text: '::..', role: 'flow.dim' }],
    [{ column: 22, text: '█', role: 'brand.medium' }, { column: 23, text: '@', role: 'flow.highlight' }, { column: 24, text: '%#*++', role: 'flow.energy' }, { column: 29, text: ':.', role: 'flow.dim' }, { column: 46, text: '::..', role: 'flow.dim' }],
    [{ column: 22, text: '█', role: 'brand.medium' }, { column: 23, text: '@', role: 'flow.highlight' }, { column: 24, text: '%#+', role: 'flow.energy' }, { column: 27, text: ':.', role: 'flow.dim' }, { column: 46, text: '::..', role: 'flow.dim' }],
    [{ column: 22, text: '█', role: 'brand.medium' }, { column: 23, text: '%*+', role: 'flow.energy' }, { column: 26, text: '.', role: 'flow.dim' }, { column: 46, text: '::.', role: 'flow.dim' }],
    [{ column: 22, text: '█', role: 'brand.medium' }, { column: 23, text: '#', role: 'flow.energy' }, { column: 24, text: ':', role: 'flow.dim' }, { column: 46, text: ':..', role: 'flow.dim' }],
    [{ column: 22, text: '█', role: 'brand.medium' }, { column: 46, text: ':..', role: 'flow.dim' }],
    [{ column: 46, text: ':.', role: 'flow.dim' }],
    [{ column: 46, text: ':.', role: 'flow.dim' }],
    [{ column: 46, text: ':.', role: 'flow.dim' }],
    [{ column: 46, text: ':', role: 'flow.dim' }],
    [{ column: 46, text: ':', role: 'flow.dim' }],
    [{ column: 46, text: ':', role: 'flow.dim' }],
    [],
    [],
    []
  ] },
  { durationMs: 70, rows: [
    [],
    [],
    [],
    [{ column: 46, text: '#', role: 'flow.energy' }],
    [{ column: 46, text: '#', role: 'flow.energy' }, { column: 47, text: ':', role: 'flow.dim' }],
    [{ column: 46, text: '#*', role: 'flow.energy' }, { column: 48, text: ':', role: 'flow.dim' }],
    [{ column: 46, text: '#*+', role: 'flow.energy' }, { column: 49, text: ':', role: 'flow.dim' }],
    [{ column: 46, text: '#*+', role: 'flow.energy' }, { column: 49, text: ':.', role: 'flow.dim' }],
    [{ column: 46, text: '##*+', role: 'flow.energy' }, { column: 50, text: ':.', role: 'flow.dim' }],
    [{ column: 22, text: '█', role: 'brand.medium' }, { column: 46, text: '##*++', role: 'flow.energy' }, { column: 51, text: ':..', role: 'flow.dim' }],
    [{ column: 22, text: '██', role: 'brand.medium' }, { column: 24, text: '#', role: 'flow.energy' }, { column: 25, text: ':', role: 'flow.dim' }, { column: 46, text: '##**+', role: 'flow.energy' }, { column: 51, text: '::..', role: 'flow.dim' }],
    [{ column: 22, text: '███', role: 'brand.medium' }, { column: 25, text: '%*', role: 'flow.energy' }, { column: 27, text: ':', role: 'flow.dim' }, { column: 46, text: '##**++', role: 'flow.energy' }, { column: 52, text: ':..', role: 'flow.dim' }],
    [{ column: 22, text: '████', role: 'brand.medium' }, { column: 26, text: '@', role: 'flow.highlight' }, { column: 27, text: '%#+', role: 'flow.energy' }, { column: 30, text: ':', role: 'flow.dim' }, { column: 46, text: '##**++', role: 'flow.energy' }, { column: 52, text: '::..', role: 'flow.dim' }],
    [{ column: 22, text: '█████', role: 'brand.medium' }, { column: 27, text: '@', role: 'flow.highlight' }, { column: 28, text: '%#*+', role: 'flow.energy' }, { column: 32, text: ':', role: 'flow.dim' }, { column: 46, text: '###**++', role: 'flow.energy' }, { column: 53, text: '::..', role: 'flow.dim' }],
    [{ column: 6, text: '███', role: 'brand.small' }, { column: 22, text: '██████', role: 'brand.medium' }, { column: 28, text: '@', role: 'flow.highlight' }, { column: 29, text: '%%#**+', role: 'flow.energy' }, { column: 35, text: ':', role: 'flow.dim' }, { column: 46, text: '###**+++', role: 'flow.energy' }, { column: 54, text: '::..', role: 'flow.dim' }],
    [{ column: 6, text: '███████', role: 'brand.small' }, { column: 22, text: '███████', role: 'brand.medium' }, { column: 29, text: '@', role: 'flow.highlight' }, { column: 30, text: '%%##*++', role: 'flow.energy' }, { column: 37, text: ':', role: 'flow.dim' }, { column: 46, text: '###***++', role: 'flow.energy' }, { column: 54, text: ':::...', role: 'flow.dim' }],
    [{ column: 6, text: '██████████', role: 'brand.small' }, { column: 22, text: '████████', role: 'brand.medium' }, { column: 30, text: '@@', role: 'flow.highlight' }, { column: 32, text: '%%##**++', role: 'flow.energy' }, { column: 40, text: ':', role: 'flow.dim' }, { column: 46, text: '###***+++', role: 'flow.energy' }, { column: 55, text: ':::...', role: 'flow.dim' }],
    [{ column: 6, text: '██████████', role: 'brand.small' }, { column: 22, text: '████████', role: 'brand.medium' }, { column: 30, text: '@@', role: 'flow.highlight' }, { column: 32, text: '%%##**++', role: 'flow.energy' }, { column: 40, text: ':', role: 'flow.dim' }, { column: 46, text: '###***+++', role: 'flow.energy' }, { column: 55, text: ':::...', role: 'flow.dim' }],
    [{ column: 6, text: '███████', role: 'brand.small' }, { column: 22, text: '███████', role: 'brand.medium' }, { column: 29, text: '@', role: 'flow.highlight' }, { column: 30, text: '%%##*++', role: 'flow.energy' }, { column: 37, text: ':', role: 'flow.dim' }, { column: 46, text: '###***++', role: 'flow.energy' }, { column: 54, text: ':::...', role: 'flow.dim' }],
    [{ column: 6, text: '███', role: 'brand.small' }, { column: 22, text: '██████', role: 'brand.medium' }, { column: 28, text: '@', role: 'flow.highlight' }, { column: 29, text: '%%#**+', role: 'flow.energy' }, { column: 35, text: ':', role: 'flow.dim' }, { column: 46, text: '###**+++', role: 'flow.energy' }, { column: 54, text: '::..', role: 'flow.dim' }],
    [{ column: 22, text: '█████', role: 'brand.medium' }, { column: 27, text: '@', role: 'flow.highlight' }, { column: 28, text: '%#*+', role: 'flow.energy' }, { column: 32, text: ':', role: 'flow.dim' }, { column: 46, text: '###**++', role: 'flow.energy' }, { column: 53, text: '::..', role: 'flow.dim' }],
    [{ column: 22, text: '████', role: 'brand.medium' }, { column: 26, text: '@', role: 'flow.highlight' }, { column: 27, text: '%#+', role: 'flow.energy' }, { column: 30, text: ':', role: 'flow.dim' }, { column: 46, text: '##**++', role: 'flow.energy' }, { column: 52, text: '::..', role: 'flow.dim' }],
    [{ column: 22, text: '███', role: 'brand.medium' }, { column: 25, text: '%*', role: 'flow.energy' }, { column: 27, text: ':', role: 'flow.dim' }, { column: 46, text: '##**++', role: 'flow.energy' }, { column: 52, text: ':..', role: 'flow.dim' }],
    [{ column: 22, text: '██', role: 'brand.medium' }, { column: 24, text: '#', role: 'flow.energy' }, { column: 25, text: ':', role: 'flow.dim' }, { column: 46, text: '##**+', role: 'flow.energy' }, { column: 51, text: '::..', role: 'flow.dim' }],
    [{ column: 22, text: '█', role: 'brand.medium' }, { column: 46, text: '##*++', role: 'flow.energy' }, { column: 51, text: ':..', role: 'flow.dim' }],
    [{ column: 46, text: '##*+', role: 'flow.energy' }, { column: 50, text: ':.', role: 'flow.dim' }],
    [{ column: 46, text: '#*+', role: 'flow.energy' }, { column: 49, text: ':.', role: 'flow.dim' }],
    [{ column: 46, text: '#*+', role: 'flow.energy' }, { column: 49, text: ':', role: 'flow.dim' }],
    [{ column: 46, text: '#*', role: 'flow.energy' }, { column: 48, text: ':', role: 'flow.dim' }],
    [{ column: 46, text: '#', role: 'flow.energy' }, { column: 47, text: ':', role: 'flow.dim' }],
    [{ column: 46, text: '#', role: 'flow.energy' }],
    [],
    [],
    []
  ] },
  { durationMs: 70, rows: [
    [],
    [],
    [],
    [{ column: 46, text: '█', role: 'brand.large' }],
    [{ column: 46, text: '█', role: 'brand.large' }, { column: 47, text: '%+', role: 'flow.energy' }],
    [{ column: 46, text: '█', role: 'brand.large' }, { column: 47, text: '@', role: 'flow.highlight' }, { column: 48, text: '#+', role: 'flow.energy' }, { column: 50, text: ':', role: 'flow.dim' }],
    [{ column: 46, text: '█', role: 'brand.large' }, { column: 47, text: '@', role: 'flow.highlight' }, { column: 48, text: '%#*', role: 'flow.energy' }, { column: 51, text: ':.', role: 'flow.dim' }],
    [{ column: 46, text: '██', role: 'brand.large' }, { column: 48, text: '@', role: 'flow.highlight' }, { column: 49, text: '%#*+', role: 'flow.energy' }, { column: 53, text: ':.', role: 'flow.dim' }],
    [{ column: 46, text: '██', role: 'brand.large' }, { column: 48, text: '@', role: 'flow.highlight' }, { column: 49, text: '%##*+', role: 'flow.energy' }, { column: 54, text: ':..', role: 'flow.dim' }],
    [{ column: 22, text: '█', role: 'brand.medium' }, { column: 46, text: '██', role: 'brand.large' }, { column: 48, text: '@@', role: 'flow.highlight' }, { column: 50, text: '%##*+', role: 'flow.energy' }, { column: 55, text: '::.', role: 'flow.dim' }],
    [{ column: 22, text: '███', role: 'brand.medium' }, { column: 25, text: '%', role: 'flow.energy' }, { column: 46, text: '███', role: 'brand.large' }, { column: 49, text: '@', role: 'flow.highlight' }, { column: 50, text: '%%##*++', role: 'flow.energy' }, { column: 57, text: '::.', role: 'flow.dim' }],
    [{ column: 22, text: '████', role: 'brand.medium' }, { column: 26, text: '@', role: 'flow.highlight' }, { column: 27, text: '%', role: 'flow.energy' }, { column: 46, text: '███', role: 'brand.large' }, { column: 49, text: '@@', role: 'flow.highlight' }, { column: 51, text: '%##**++', role: 'flow.energy' }, { column: 58, text: ':..', role: 'flow.dim' }],
    [{ column: 22, text: '███████', role: 'brand.medium' }, { column: 29, text: '@', role: 'flow.highlight' }, { column: 30, text: '%', role: 'flow.energy' }, { column: 46, text: '███', role: 'brand.large' }, { column: 49, text: '@@', role: 'flow.highlight' }, { column: 51, text: '%%##**++', role: 'flow.energy' }, { column: 59, text: '::..', role: 'flow.dim' }],
    [{ column: 22, text: '████████', role: 'brand.medium' }, { column: 30, text: '@', role: 'flow.highlight' }, { column: 31, text: '%%', role: 'flow.energy' }, { column: 46, text: '███', role: 'brand.large' }, { column: 49, text: '@@@', role: 'flow.highlight' }, { column: 52, text: '%%##**++', role: 'flow.energy' }, { column: 60, text: ':::..', role: 'flow.dim' }],
    [{ column: 6, text: '███', role: 'brand.small' }, { column: 22, text: '███████████', role: 'brand.medium' }, { column: 33, text: '@', role: 'flow.highlight' }, { column: 34, text: '%%', role: 'flow.energy' }, { column: 46, text: '████', role: 'brand.large' }, { column: 50, text: '@@', role: 'flow.highlight' }, { column: 52, text: '%%###**+++', role: 'flow.energy' }, { column: 62, text: '::...', role: 'flow.dim' }],
    [{ column: 6, text: '███████', role: 'brand.small' }, { column: 22, text: '████████████', role: 'brand.medium' }, { column: 34, text: '@@', role: 'flow.highlight' }, { column: 36, text: '%%', role: 'flow.energy' }, { column: 46, text: '████', role: 'brand.large' }, { column: 50, text: '@@@', role: 'flow.highlight' }, { column: 53, text: '%%###**+++', role: 'flow.energy' }, { column: 63, text: ':::..', role: 'flow.dim' }],
    [{ column: 6, text: '██████████', role: 'brand.small' }, { column: 22, text: '███████████████', role: 'brand.medium' }, { column: 37, text: '@@', role: 'flow.highlight' }, { column: 39, text: '%%', role: 'flow.energy' }, { column: 46, text: '████', role: 'brand.large' }, { column: 50, text: '@@@', role: 'flow.highlight' }, { column: 53, text: '%%%###***++', role: 'flow.energy' }, { column: 64, text: ':::...', role: 'flow.dim' }],
    [{ column: 6, text: '██████████', role: 'brand.small' }, { column: 22, text: '███████████████', role: 'brand.medium' }, { column: 37, text: '@@', role: 'flow.highlight' }, { column: 39, text: '%%', role: 'flow.energy' }, { column: 46, text: '████', role: 'brand.large' }, { column: 50, text: '@@@', role: 'flow.highlight' }, { column: 53, text: '%%%###***++', role: 'flow.energy' }, { column: 64, text: ':::...', role: 'flow.dim' }],
    [{ column: 6, text: '███████', role: 'brand.small' }, { column: 22, text: '████████████', role: 'brand.medium' }, { column: 34, text: '@@', role: 'flow.highlight' }, { column: 36, text: '%%', role: 'flow.energy' }, { column: 46, text: '████', role: 'brand.large' }, { column: 50, text: '@@@', role: 'flow.highlight' }, { column: 53, text: '%%###**+++', role: 'flow.energy' }, { column: 63, text: ':::..', role: 'flow.dim' }],
    [{ column: 6, text: '███', role: 'brand.small' }, { column: 22, text: '███████████', role: 'brand.medium' }, { column: 33, text: '@', role: 'flow.highlight' }, { column: 34, text: '%%', role: 'flow.energy' }, { column: 46, text: '████', role: 'brand.large' }, { column: 50, text: '@@', role: 'flow.highlight' }, { column: 52, text: '%%###**+++', role: 'flow.energy' }, { column: 62, text: '::...', role: 'flow.dim' }],
    [{ column: 22, text: '████████', role: 'brand.medium' }, { column: 30, text: '@', role: 'flow.highlight' }, { column: 31, text: '%%', role: 'flow.energy' }, { column: 46, text: '███', role: 'brand.large' }, { column: 49, text: '@@@', role: 'flow.highlight' }, { column: 52, text: '%%##**++', role: 'flow.energy' }, { column: 60, text: ':::..', role: 'flow.dim' }],
    [{ column: 22, text: '███████', role: 'brand.medium' }, { column: 29, text: '@', role: 'flow.highlight' }, { column: 30, text: '%', role: 'flow.energy' }, { column: 46, text: '███', role: 'brand.large' }, { column: 49, text: '@@', role: 'flow.highlight' }, { column: 51, text: '%%##**++', role: 'flow.energy' }, { column: 59, text: '::..', role: 'flow.dim' }],
    [{ column: 22, text: '████', role: 'brand.medium' }, { column: 26, text: '@', role: 'flow.highlight' }, { column: 27, text: '%', role: 'flow.energy' }, { column: 46, text: '███', role: 'brand.large' }, { column: 49, text: '@@', role: 'flow.highlight' }, { column: 51, text: '%##**++', role: 'flow.energy' }, { column: 58, text: ':..', role: 'flow.dim' }],
    [{ column: 22, text: '███', role: 'brand.medium' }, { column: 25, text: '%', role: 'flow.energy' }, { column: 46, text: '███', role: 'brand.large' }, { column: 49, text: '@', role: 'flow.highlight' }, { column: 50, text: '%%##*++', role: 'flow.energy' }, { column: 57, text: '::.', role: 'flow.dim' }],
    [{ column: 22, text: '█', role: 'brand.medium' }, { column: 46, text: '██', role: 'brand.large' }, { column: 48, text: '@@', role: 'flow.highlight' }, { column: 50, text: '%##*+', role: 'flow.energy' }, { column: 55, text: '::.', role: 'flow.dim' }],
    [{ column: 46, text: '██', role: 'brand.large' }, { column: 48, text: '@', role: 'flow.highlight' }, { column: 49, text: '%##*+', role: 'flow.energy' }, { column: 54, text: ':..', role: 'flow.dim' }],
    [{ column: 46, text: '██', role: 'brand.large' }, { column: 48, text: '@', role: 'flow.highlight' }, { column: 49, text: '%#*+', role: 'flow.energy' }, { column: 53, text: ':.', role: 'flow.dim' }],
    [{ column: 46, text: '█', role: 'brand.large' }, { column: 47, text: '@', role: 'flow.highlight' }, { column: 48, text: '%#*', role: 'flow.energy' }, { column: 51, text: ':.', role: 'flow.dim' }],
    [{ column: 46, text: '█', role: 'brand.large' }, { column: 47, text: '@', role: 'flow.highlight' }, { column: 48, text: '#+', role: 'flow.energy' }, { column: 50, text: ':', role: 'flow.dim' }],
    [{ column: 46, text: '█', role: 'brand.large' }, { column: 47, text: '%+', role: 'flow.energy' }],
    [{ column: 46, text: '█', role: 'brand.large' }],
    [],
    [],
    []
  ] },
  { durationMs: 75, rows: [
    [],
    [],
    [],
    [{ column: 46, text: '█', role: 'brand.large' }, { column: 47, text: '+', role: 'flow.energy' }],
    [{ column: 46, text: '██', role: 'brand.large' }, { column: 48, text: '%+', role: 'flow.energy' }],
    [{ column: 46, text: '███', role: 'brand.large' }, { column: 49, text: '@', role: 'flow.highlight' }, { column: 50, text: '#+', role: 'flow.energy' }],
    [{ column: 46, text: '████', role: 'brand.large' }, { column: 50, text: '@', role: 'flow.highlight' }, { column: 51, text: '%*+', role: 'flow.energy' }],
    [{ column: 46, text: '█████', role: 'brand.large' }, { column: 51, text: '@', role: 'flow.highlight' }, { column: 52, text: '%#*+', role: 'flow.energy' }],
    [{ column: 46, text: '██████', role: 'brand.large' }, { column: 52, text: '@', role: 'flow.highlight' }, { column: 53, text: '%%#*+', role: 'flow.energy' }],
    [{ column: 22, text: '█', role: 'brand.medium' }, { column: 46, text: '███████', role: 'brand.large' }, { column: 53, text: '@@', role: 'flow.highlight' }, { column: 55, text: '%#**+', role: 'flow.energy' }],
    [{ column: 22, text: '████', role: 'brand.medium' }, { column: 46, text: '████████', role: 'brand.large' }, { column: 54, text: '@@', role: 'flow.highlight' }, { column: 56, text: '%##**+', role: 'flow.energy' }],
    [{ column: 22, text: '██████', role: 'brand.medium' }, { column: 46, text: '█████████', role: 'brand.large' }, { column: 55, text: '@', role: 'flow.highlight' }, { column: 56, text: '%%##**+', role: 'flow.energy' }],
    [{ column: 22, text: '█████████', role: 'brand.medium' }, { column: 46, text: '██████████', role: 'brand.large' }, { column: 56, text: '@@', role: 'flow.highlight' }, { column: 58, text: '%%##**+', role: 'flow.energy' }],
    [{ column: 22, text: '███████████', role: 'brand.medium' }, { column: 46, text: '███████████', role: 'brand.large' }, { column: 57, text: '@@', role: 'flow.highlight' }, { column: 59, text: '%%##**++', role: 'flow.energy' }],
    [{ column: 6, text: '███', role: 'brand.small' }, { column: 22, text: '██████████████', role: 'brand.medium' }, { column: 46, text: '████████████', role: 'brand.large' }, { column: 58, text: '@@', role: 'flow.highlight' }, { column: 60, text: '%%%##**++', role: 'flow.energy' }],
    [{ column: 6, text: '███████', role: 'brand.small' }, { column: 22, text: '████████████████', role: 'brand.medium' }, { column: 46, text: '█████████████', role: 'brand.large' }, { column: 59, text: '@@', role: 'flow.highlight' }, { column: 61, text: '%%%###**++', role: 'flow.energy' }],
    [{ column: 6, text: '██████████', role: 'brand.small' }, { column: 22, text: '███████████████████', role: 'brand.medium' }, { column: 46, text: '██████████████', role: 'brand.large' }, { column: 60, text: '@@@', role: 'flow.highlight' }, { column: 63, text: '%%###***++', role: 'flow.energy' }],
    [{ column: 6, text: '██████████', role: 'brand.small' }, { column: 22, text: '███████████████████', role: 'brand.medium' }, { column: 46, text: '██████████████', role: 'brand.large' }, { column: 60, text: '@@@', role: 'flow.highlight' }, { column: 63, text: '%%###***++', role: 'flow.energy' }],
    [{ column: 6, text: '███████', role: 'brand.small' }, { column: 22, text: '████████████████', role: 'brand.medium' }, { column: 46, text: '█████████████', role: 'brand.large' }, { column: 59, text: '@@', role: 'flow.highlight' }, { column: 61, text: '%%%###**++', role: 'flow.energy' }],
    [{ column: 6, text: '███', role: 'brand.small' }, { column: 22, text: '██████████████', role: 'brand.medium' }, { column: 46, text: '████████████', role: 'brand.large' }, { column: 58, text: '@@', role: 'flow.highlight' }, { column: 60, text: '%%%##**++', role: 'flow.energy' }],
    [{ column: 22, text: '███████████', role: 'brand.medium' }, { column: 46, text: '███████████', role: 'brand.large' }, { column: 57, text: '@@', role: 'flow.highlight' }, { column: 59, text: '%%##**++', role: 'flow.energy' }],
    [{ column: 22, text: '█████████', role: 'brand.medium' }, { column: 46, text: '██████████', role: 'brand.large' }, { column: 56, text: '@@', role: 'flow.highlight' }, { column: 58, text: '%%##**+', role: 'flow.energy' }],
    [{ column: 22, text: '██████', role: 'brand.medium' }, { column: 46, text: '█████████', role: 'brand.large' }, { column: 55, text: '@', role: 'flow.highlight' }, { column: 56, text: '%%##**+', role: 'flow.energy' }],
    [{ column: 22, text: '████', role: 'brand.medium' }, { column: 46, text: '████████', role: 'brand.large' }, { column: 54, text: '@@', role: 'flow.highlight' }, { column: 56, text: '%##**+', role: 'flow.energy' }],
    [{ column: 22, text: '█', role: 'brand.medium' }, { column: 46, text: '███████', role: 'brand.large' }, { column: 53, text: '@@', role: 'flow.highlight' }, { column: 55, text: '%#**+', role: 'flow.energy' }],
    [{ column: 46, text: '██████', role: 'brand.large' }, { column: 52, text: '@', role: 'flow.highlight' }, { column: 53, text: '%%#*+', role: 'flow.energy' }],
    [{ column: 46, text: '█████', role: 'brand.large' }, { column: 51, text: '@', role: 'flow.highlight' }, { column: 52, text: '%#*+', role: 'flow.energy' }],
    [{ column: 46, text: '████', role: 'brand.large' }, { column: 50, text: '@', role: 'flow.highlight' }, { column: 51, text: '%*+', role: 'flow.energy' }],
    [{ column: 46, text: '███', role: 'brand.large' }, { column: 49, text: '@', role: 'flow.highlight' }, { column: 50, text: '#+', role: 'flow.energy' }],
    [{ column: 46, text: '██', role: 'brand.large' }, { column: 48, text: '%+', role: 'flow.energy' }],
    [{ column: 46, text: '█', role: 'brand.large' }, { column: 47, text: '+', role: 'flow.energy' }],
    [],
    [],
    []
  ] },
  { durationMs: 80, rows: [
    [],
    [],
    [],
    [{ column: 46, text: '█', role: 'brand.large' }, { column: 47, text: '%', role: 'flow.energy' }],
    [{ column: 46, text: '███', role: 'brand.large' }, { column: 49, text: '%', role: 'flow.energy' }],
    [{ column: 46, text: '█████', role: 'brand.large' }, { column: 51, text: '%', role: 'flow.energy' }],
    [{ column: 46, text: '███████', role: 'brand.large' }, { column: 53, text: '%', role: 'flow.energy' }],
    [{ column: 46, text: '████████', role: 'brand.large' }, { column: 54, text: '@', role: 'flow.highlight' }, { column: 55, text: '%', role: 'flow.energy' }],
    [{ column: 46, text: '██████████', role: 'brand.large' }, { column: 56, text: '@', role: 'flow.highlight' }, { column: 57, text: '%', role: 'flow.energy' }],
    [{ column: 22, text: '█', role: 'brand.medium' }, { column: 46, text: '████████████', role: 'brand.large' }, { column: 58, text: '@', role: 'flow.highlight' }, { column: 59, text: '%', role: 'flow.energy' }],
    [{ column: 22, text: '████', role: 'brand.medium' }, { column: 46, text: '██████████████', role: 'brand.large' }, { column: 60, text: '@', role: 'flow.highlight' }, { column: 61, text: '%', role: 'flow.energy' }],
    [{ column: 22, text: '██████', role: 'brand.medium' }, { column: 46, text: '██████████████', role: 'brand.large' }, { column: 60, text: '@@', role: 'flow.highlight' }, { column: 62, text: '%', role: 'flow.energy' }],
    [{ column: 22, text: '█████████', role: 'brand.medium' }, { column: 46, text: '████████████████', role: 'brand.large' }, { column: 62, text: '@@', role: 'flow.highlight' }, { column: 64, text: '%', role: 'flow.energy' }],
    [{ column: 22, text: '███████████', role: 'brand.medium' }, { column: 46, text: '██████████████████', role: 'brand.large' }, { column: 64, text: '@@', role: 'flow.highlight' }, { column: 66, text: '%', role: 'flow.energy' }],
    [{ column: 6, text: '███', role: 'brand.small' }, { column: 22, text: '██████████████', role: 'brand.medium' }, { column: 46, text: '████████████████████', role: 'brand.large' }, { column: 66, text: '@@', role: 'flow.highlight' }, { column: 68, text: '%', role: 'flow.energy' }],
    [{ column: 6, text: '███████', role: 'brand.small' }, { column: 22, text: '████████████████', role: 'brand.medium' }, { column: 46, text: '█████████████████████', role: 'brand.large' }, { column: 67, text: '@@@', role: 'flow.highlight' }, { column: 70, text: '%', role: 'flow.energy' }],
    [{ column: 6, text: '██████████', role: 'brand.small' }, { column: 22, text: '███████████████████', role: 'brand.medium' }, { column: 46, text: '███████████████████████', role: 'brand.large' }, { column: 69, text: '@@@', role: 'flow.highlight' }, { column: 72, text: '%', role: 'flow.energy' }],
    [{ column: 6, text: '██████████', role: 'brand.small' }, { column: 22, text: '███████████████████', role: 'brand.medium' }, { column: 46, text: '███████████████████████', role: 'brand.large' }, { column: 69, text: '@@@', role: 'flow.highlight' }, { column: 72, text: '%', role: 'flow.energy' }],
    [{ column: 6, text: '███████', role: 'brand.small' }, { column: 22, text: '████████████████', role: 'brand.medium' }, { column: 46, text: '█████████████████████', role: 'brand.large' }, { column: 67, text: '@@@', role: 'flow.highlight' }, { column: 70, text: '%', role: 'flow.energy' }],
    [{ column: 6, text: '███', role: 'brand.small' }, { column: 22, text: '██████████████', role: 'brand.medium' }, { column: 46, text: '████████████████████', role: 'brand.large' }, { column: 66, text: '@@', role: 'flow.highlight' }, { column: 68, text: '%', role: 'flow.energy' }],
    [{ column: 22, text: '███████████', role: 'brand.medium' }, { column: 46, text: '██████████████████', role: 'brand.large' }, { column: 64, text: '@@', role: 'flow.highlight' }, { column: 66, text: '%', role: 'flow.energy' }],
    [{ column: 22, text: '█████████', role: 'brand.medium' }, { column: 46, text: '████████████████', role: 'brand.large' }, { column: 62, text: '@@', role: 'flow.highlight' }, { column: 64, text: '%', role: 'flow.energy' }],
    [{ column: 22, text: '██████', role: 'brand.medium' }, { column: 46, text: '██████████████', role: 'brand.large' }, { column: 60, text: '@@', role: 'flow.highlight' }, { column: 62, text: '%', role: 'flow.energy' }],
    [{ column: 22, text: '████', role: 'brand.medium' }, { column: 46, text: '██████████████', role: 'brand.large' }, { column: 60, text: '@', role: 'flow.highlight' }, { column: 61, text: '%', role: 'flow.energy' }],
    [{ column: 22, text: '█', role: 'brand.medium' }, { column: 46, text: '████████████', role: 'brand.large' }, { column: 58, text: '@', role: 'flow.highlight' }, { column: 59, text: '%', role: 'flow.energy' }],
    [{ column: 46, text: '██████████', role: 'brand.large' }, { column: 56, text: '@', role: 'flow.highlight' }, { column: 57, text: '%', role: 'flow.energy' }],
    [{ column: 46, text: '████████', role: 'brand.large' }, { column: 54, text: '@', role: 'flow.highlight' }, { column: 55, text: '%', role: 'flow.energy' }],
    [{ column: 46, text: '███████', role: 'brand.large' }, { column: 53, text: '%', role: 'flow.energy' }],
    [{ column: 46, text: '█████', role: 'brand.large' }, { column: 51, text: '%', role: 'flow.energy' }],
    [{ column: 46, text: '███', role: 'brand.large' }, { column: 49, text: '%', role: 'flow.energy' }],
    [{ column: 46, text: '█', role: 'brand.large' }, { column: 47, text: '%', role: 'flow.energy' }],
    [],
    [],
    []
  ] },
  { durationMs: 0, rows: [
    [],
    [],
    [],
    [{ column: 46, text: '██', role: 'brand.large' }],
    [{ column: 46, text: '████', role: 'brand.large' }],
    [{ column: 46, text: '██████', role: 'brand.large' }],
    [{ column: 46, text: '████████', role: 'brand.large' }],
    [{ column: 46, text: '██████████', role: 'brand.large' }],
    [{ column: 46, text: '████████████', role: 'brand.large' }],
    [{ column: 22, text: '█', role: 'brand.medium' }, { column: 46, text: '██████████████', role: 'brand.large' }],
    [{ column: 22, text: '████', role: 'brand.medium' }, { column: 46, text: '████████████████', role: 'brand.large' }],
    [{ column: 22, text: '██████', role: 'brand.medium' }, { column: 46, text: '█████████████████', role: 'brand.large' }],
    [{ column: 22, text: '█████████', role: 'brand.medium' }, { column: 46, text: '███████████████████', role: 'brand.large' }],
    [{ column: 22, text: '███████████', role: 'brand.medium' }, { column: 46, text: '█████████████████████', role: 'brand.large' }],
    [{ column: 6, text: '███', role: 'brand.small' }, { column: 22, text: '██████████████', role: 'brand.medium' }, { column: 46, text: '███████████████████████', role: 'brand.large' }],
    [{ column: 6, text: '███████', role: 'brand.small' }, { column: 22, text: '████████████████', role: 'brand.medium' }, { column: 46, text: '█████████████████████████', role: 'brand.large' }],
    [{ column: 6, text: '██████████', role: 'brand.small' }, { column: 22, text: '███████████████████', role: 'brand.medium' }, { column: 46, text: '███████████████████████████', role: 'brand.large' }],
    [{ column: 6, text: '██████████', role: 'brand.small' }, { column: 22, text: '███████████████████', role: 'brand.medium' }, { column: 46, text: '███████████████████████████', role: 'brand.large' }],
    [{ column: 6, text: '███████', role: 'brand.small' }, { column: 22, text: '████████████████', role: 'brand.medium' }, { column: 46, text: '█████████████████████████', role: 'brand.large' }],
    [{ column: 6, text: '███', role: 'brand.small' }, { column: 22, text: '██████████████', role: 'brand.medium' }, { column: 46, text: '███████████████████████', role: 'brand.large' }],
    [{ column: 22, text: '███████████', role: 'brand.medium' }, { column: 46, text: '█████████████████████', role: 'brand.large' }],
    [{ column: 22, text: '█████████', role: 'brand.medium' }, { column: 46, text: '███████████████████', role: 'brand.large' }],
    [{ column: 22, text: '██████', role: 'brand.medium' }, { column: 46, text: '█████████████████', role: 'brand.large' }],
    [{ column: 22, text: '████', role: 'brand.medium' }, { column: 46, text: '████████████████', role: 'brand.large' }],
    [{ column: 22, text: '█', role: 'brand.medium' }, { column: 46, text: '██████████████', role: 'brand.large' }],
    [{ column: 46, text: '████████████', role: 'brand.large' }],
    [{ column: 46, text: '██████████', role: 'brand.large' }],
    [{ column: 46, text: '████████', role: 'brand.large' }],
    [{ column: 46, text: '██████', role: 'brand.large' }],
    [{ column: 46, text: '████', role: 'brand.large' }],
    [{ column: 46, text: '██', role: 'brand.large' }],
    [],
    [],
    []
  ] },
] } as const;
